### ISSUE TITLE
Validation with schema: formState isValid attribute not return correct result

### ISSUE THREAD

**Issue by bluebill1049** [bluebill1049/react-hook-form#117]
Not sure if related to this but I've noticed that `isValid` on `formState` doesn't update when using external validation schema (yup in this case) and `onUpdate` mode.

Here's a codesadbox: https://codesandbox.io/s/react-hook-form-seterror-ftvrr

This example has two fields, each required. They start off as filled in via `defaultValue` and the form is valid. Now try to edit the form and clear the password confirmation input. The form is still valid. If you press the TEST button the form becomes invalid.

Now if you change the mode to `onChange` or `onBlur` it works as expected, clearing the input causes the form to become invalid.

_Originally posted by @bowd in https://github.com/bluebill1049/react-hook-form/issues/92#issuecomment-508660645_

**Comment by bluebill1049** [comment]
there is no `onUpdate` mode

**Comment by bluebill1049** [comment]
I dont think `isValid` is set up correctly for validation with schema, looking into the problem.

**Comment by bluebill1049** [comment]
@bowThink I have fixed the issue.

https://codesandbox.io/s/react-hook-form-seterror-wysuq

**Comment by bluebill1049** [comment]
looks like this is fixed now.

`https://codesandbox.io/s/react-hook-form-seterror-wysuq`

- fixed: there is a bug where errors not clear after submitting.

> but there is no `onUpdate` mode
> and one of your fields doesn't have the required attribute.

**Comment by bowd** [comment]
Sorry I made a mixup with `onChange` / `onUpdate`. Actually, I'm still having an issue. So, first of all, I did have required because I changed the example to use `yup` and provided a validation schema, not inline require on the `register` method. 

But now I'm seeing some behavior that's a bit inconsistent. 

Let's look at this one: `https://codesandbox.io/s/react-hook-form-seterror-mo8sh`.
What I want to achieve is to have two inputs and a button that only shows up when the form is actually filled and valid. In this case I have hidden the submit button behind a `formState.isValid`. 
When the page loads you see the inputs and isValid is false. After you write in the first input isValid becomes true even if the 2nd input is empty. If you click in and out of it it gets an error but the form still has isValid = true even if there are errors shown in the console.

P.S. I updated the sandbox to the latest pulished version of the library.

**Comment by bluebill1049** [comment]
thanks @bowd i think this fix the issue 

https://codesandbox.io/s/react-hook-form-seterror-n2dvh

can you check?

**Comment by bowd** [comment]
@bluebill1049 it works in your sandbox but I don't see any difference at all from the one I shared. What did you change to make it work?

**Comment by bluebill1049** [comment]
cool, it works :) I will commit my change and publish it today 👍

**Comment by bluebill1049** [comment]
published: react-hook-form@3.17.4 thanks for report the issue

**Comment by bluebill1049** [comment]
hey, @bowd let me know if I have fixed the issue and we can close this :)

**Comment by bowd** [comment]
There's still a problem. When adding `defaultValue` to the example above `formState.isValid` stays false until you actually click (touch) one of the inputs. If the form is actually valid based on all the `defaultValues` I think the state should reflect that. I've tried forcing a manual `triggerValidation` in an effect and it's still not valid until I blur an input.

`https://codesandbox.io/s/react-hook-form-seterror-5b464`

**Comment by bluebill1049** [comment]
`triggerValidation` should do the the job, let me check. sorry about the bug haven't spend enough love with `Yup` and schema validation

**Comment by bowd** [comment]
No worries, I appreciate you being so responsive and on top of things 🚀. Code is always gonna break that's the nature of it, the people behind it are important.

**Comment by bluebill1049** [comment]
@bowd looks like it's working: https://codesandbox.io/s/react-hook-form-seterror-rfdgd

could you please help on a quick test?

**Comment by bowd** [comment]
So it does work in the sense that when `defaultValue` is set on all fields and you do kickoff the `triggerValidation` manually all looks ok. But this doesn't really work well if you have a partially filled form or an empty form, because it shows all errors from the start even if you haven't touched the field, which isn't ideal. The current workaround in my case would be to only trigger the `triggerValidation` and what would be an "edit" form where I know I'm preloading with values that make a valid form.

In an ideal world maybe there should be a decoupling between the errors on the field level and the `isValid` state of the form. So that, for example, I would be able to tell that the form is _not_ valid while still not necessarily showing any errors yet. Otherwise, I think I could use `touched` to only show errors on fields that have been touched. Which is actually the best approach for now, so I would say that the fix is good and we can close this :+1:

**Comment by bluebill1049** [comment]
thanks a lot for your testing @bowd, I will write some unit tests and publish it tomorrow. will keep you in the loop.

**Comment by bluebill1049** [comment]
@bowd fix has been merged, will test tmr morning again and release

**Comment by bluebill1049** [comment]
@bowd https://github.com/bluebill1049/react-hook-form/releases/tag/v3.17.5 once you happy with it please close the issue 🙏

**Comment by bluebill1049** [comment]
it's release 👍 let me know if things work out for you and we can close this issue 🙏

**Comment by bowd** [comment]
All is well, you can close the issue. Thanks!
